name: Create Release

on:
  workflow_dispatch: { }

permissions: { }

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    steps:
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
      with:
        persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # tag=v3.12.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Perform Release
      run: |-
        git config user.name "dependencytrack-bot"
        git config user.email "106437498+dependencytrack-bot@users.noreply.github.com"
        mvn -B release:prepare
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.BOT_RELEASE_TOKEN }}
        tags: true
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: "${{ secrets.BOT_RELEASE_TOKEN }}"
      run: |-
        gh release create "$(sed -nr 's/^scm.tag=(v[0-9.]+)$/\1/p' release.properties)" \
          --target ${{ github.ref_name }} \
          --verify-tag \
          --generate-notes
